version: "3"
services:
  blockchain:
    container_name: blockchain
    image: arianeetech/arianee-rpc-server-blockchain
    entrypoint: ["node", "/app/ganache-core.docker.cli.js", "--deterministic", "-g", "1", "-e", "100", "--gasLimit", "8000000", "--db", "/usr/src/app"]
    ports:
      - 8545:8545
  arianee-privacy-gateway:
    container_name: arianee-privacy-gateway
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
