FROM node:16.14.2

WORKDIR /var/www

COPY ./package*.json ./
COPY ./tsconfig.json ./tsconfig.json
COPY ./src ./src

RUN ["npm", "install"]
RUN ["npm", "run", "build"]
EXPOSE 3000
CMD ["npm","run", "start:express"]
