# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  build-and-test-uat:
    machine:
      image: ubuntu-1604:202104-01
    resource_class: large
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Declare domain blockchain
          command: echo 127.0.0.1 blockchain | sudo tee -a /etc/hosts
      - run:
          name: Launch docker
          command: docker-compose up --detach --force-recreate
      - run:
          name: Run tests
          command: npm run test
workflows:
  sample:
    jobs:
      - build-and-test-uat
